name: CI

on:
  pull_request:
    types: [closed]
  issue_comment:
    types: [created]
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
      - name: "Comment PR"
        uses: actions/github-script@0.3.0
        env:
          MESSAGE: "Hello!!!"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { MESSAGE: message } = process.env;
            const { repo: { owner, repo }  } = context;
            const { data: comments } = await github.issues.listComments({ owner, repo, issue_number: 4 })
            
            console.log(comments);

            if(comments && comments.length && comments.find(c => c.body === message)) return;

            github.issues.createComment({ issue_number: 4, owner, repo, body: message });

  pr-comment:
    runs-on: ubuntu-latest

    if: ${{ github.event.issue.pull_request && github.event.action != 'closed' && github.event.comment.body == 'preview' }}

    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
      - name: "Comment PR"
        uses: actions/github-script@0.3.0
        env:
          MESSAGE: "Hello!!"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { MESSAGE: message } = process.env;
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const comments = await github.issues.listComments({ owner, repo, issue_number })

            if(comments && comments.find(c => c.body === message)) return;

            github.issues.createComment({ issue_number, owner, repo, body: message });

  pr-close:
    runs-on: ubuntu-latest

    if: ${{ github.event.action == 'closed' }}

    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
