name: CI

on:
  pull_request:
    types: [closed]
  issue_comment:
    types: [created]

jobs:
  pr-comment:
    runs-on: ubuntu-latest

    if: ${{ github.event.issue.pull_request && github.event.action != 'closed' && github.event.comment.body == 'preview' }}

    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Hey there!!'
          pr_number: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-close:
    runs-on: ubuntu-latest

    if: ${{ github.event.action == 'closed' }}

    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
